# Generated by Django 5.2 on 2025-05-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liberian',
            fields=[
                ('UserName', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('LiberianID', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('UserName', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('StaffID', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DateJoined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('UserName', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('MatriculationNumber', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DateJoined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('DatePublished', models.DateField()),
                ('CopiesOwned', models.IntegerField()),
                ('AuthorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.author')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorrowID', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('BorrowedDate', models.DateField(auto_now_add=True)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.book')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
