# Generated by Django 5.2 on 2025-05-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_remove_liberian_username_remove_staff_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='id',
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='object_id',
        ),
        migrations.AddField(
            model_name='borrowed',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.staff'),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.student'),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='BorrowID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
