# Generated by Django 5.2 on 2025-05-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_remove_borrowed_content_type_remove_borrowed_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Not Active', 'Not Active')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Not Active', 'Not Active')], default='Active', max_length=20),
        ),
    ]
