# Generated by Django 5.2 on 2025-05-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_staff_status_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='AuthorID',
        ),
        migrations.AddField(
            model_name='book',
            name='Authors',
            field=models.ManyToManyField(to='LMS.author'),
        ),
    ]
