# Generated by Django 5.2 on 2025-05-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_remove_book_authorid_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='Category',
        ),
        migrations.AddField(
            model_name='book',
            name='Categories',
            field=models.ManyToManyField(to='LMS.category'),
        ),
    ]
