# Generated by Django 5.2 on 2025-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_category_remove_book_category_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='AuthorID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
